from __future__ import annotations

KNOWLEDGE_ELEMENTS = [
    "Administration and Management",
    "Administrative",
    "Biology",
    "Building and Construction",
    "Chemistry",
    "Clerical",
    "Communications and Media",
    "Computers and Electronics",
    "Customer and Personal Service",
    "Design",
    "Economics and Accounting",
    "Education and Training",
    "Engineering and Technology",
    "English Language",
    "Fine Arts",
    "Food Production",
    "Foreign Language",
    "Geography",
    "History and Archeology",
    "Law and Government",
    "Mathematics",
    "Mechanical",
    "Medicine and Dentistry",
    "Philosophy and Theology",
    "Physics",
    "Production and Processing",
    "Psychology",
    "Public Safety and Security",
    "Sales and Marketing",
    "Sociology and Anthropology",
    "Telecommunications",
    "Therapy and Counseling",
    "Transportation",
]

SKILL_ELEMENTS = [
    "Reading Comprehension",
    "Active Listening",
    "Writing",
    "Speaking",
    "Mathematics",
    "Science",
    "Critical Thinking",
    "Active Learning",
    "Learning Strategies",
    "Monitoring",
    "Social Perceptiveness",
    "Coordination",
    "Persuasion",
    "Negotiation",
    "Instructing",
    "Service Orientation",
    "Complex Problem Solving",
    "Operations Analysis",
    "Technology Design",
    "Equipment Selection",
    "Installation",
    "Programming",
    "Operation Monitoring",
    "Operation and Control",
    "Equipment Maintenance",
    "Troubleshooting",
    "Repairing",
    "Quality Control Analysis",
    "Judgment and Decision Making",
    "Systems Analysis",
    "Systems Evaluation",
    "Time Management",
    "Management of Financial Resources",
    "Management of Material Resources",
    "Management of Personnel Resources",
]

WORK_STYLE_ELEMENTS = [
    "Achievement Orientation",
    "Adaptability",
    "Attention to Detail",
    "Cautiousness",
    "Cooperation",
    "Dependability",
    "Empathy",
    "Humility",
    "Initiative",
    "Innovation",
    "Integrity",
    "Intellectual Curiosity",
    "Leadership Orientation",
    "Optimism",
    "Perseverance",
    "Self-Confidence",
    "Self-Control",
    "Sincerity",
    "Social Orientation",
    "Stress Tolerance",
    "Tolerance for Ambiguity",
]

CAREER_NODE_TYPES = {
    "knowledge",
    "skill",
    "tool",
    "behavioral_trait",
    "project",
    "course",
    "career_goal",
    "interest",
    "constraint",
    "implicit_signal",
}

